mei: fix compilation error with missing WATCHDOG_CORE
Kconfig is not transitive so INTEL_ME_TXE has to depend
on WATCHDOG_CORE as well

ERROR: "watchdog_unregister_device" [drivers/misc/mei/mei.ko]
undefined!
ERROR: "watchdog_register_device" [drivers/misc/mei/mei.ko]
undefined!

Issue: APDEV-1603
Change-Id: Id2a2c625a9844c11a6df825a5b32ca108bad705f
Reported-by: Fengguang Wu <fengguang.wu@intel.com>
Signed-off-by: Tomas Winkler <tomas.winkler@intel.com>
Reviewed-on: https://android.intel.com/162968
Reviewed-by: Nordell, Joakim <joakim.nordell@intel.com>
Tested-by: sys_abtbuild <sys_abtbuild@intel.com>
Reviewed-by: Lilja, Ola <ola.lilja@intel.com>